## Prepare Iris Dataset

In [1]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

In [2]:
iris = pd.DataFrame()
iris_from_file = datasets.load_iris()

for column_name, row in zip(iris_from_file['feature_names'], iris_from_file['data'].T):
    iris[column_name] = row
iris["target"] = iris_from_file["target"]

Potential "gotcha": categories[i] are the categories in the ith column.  So if we have only one column to transform, then we still need to pass a list containing the the single list describing those categories

In [3]:
iris_target_ohe = OneHotEncoder(categories=[[0, 1, 2]], sparse=False)
iris_target_ohe_data = iris_target_ohe.fit_transform(iris["target"].to_numpy().reshape(-1, 1))
for column_name, row in zip(["0", "1", "2"], iris_target_ohe_data.T):
    iris[column_name] = row.astype("int")

In [4]:
iris_train, iris_test = train_test_split(iris, train_size=0.7, random_state=1)

## Logistic Regression-- Sklearn

In [5]:
from sklearn.linear_model import LogisticRegression

In [6]:
lrc = LogisticRegression()
lrc.fit(iris_train[iris_from_file["feature_names"]], iris_train["target"])

LogisticRegression()

In [7]:
from sklearn.metrics import confusion_matrix

In [8]:
confusion_matrix(iris_train["target"], lrc.predict(iris_train[iris_from_file["feature_names"]]))

array([[36,  0,  0],
       [ 0, 30,  2],
       [ 0,  0, 37]])

In [9]:
confusion_matrix(iris_test["target"], lrc.predict(iris_test[iris_from_file["feature_names"]]))

array([[14,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 13]])

## Logistic Regression-- Sklearn (with Regularization)

In [10]:
lrc_2 = LogisticRegression(penalty='l2', C=0.1)
lrc_2.fit(iris_train[iris_from_file["feature_names"]], iris_train["target"])

LogisticRegression(C=0.1)

In [11]:
confusion_matrix(iris_train["target"], lrc_2.predict(iris_train[iris_from_file["feature_names"]]))

array([[36,  0,  0],
       [ 0, 26,  6],
       [ 0,  1, 36]])

In [12]:
confusion_matrix(iris_test["target"], lrc_2.predict(iris_test[iris_from_file["feature_names"]]))

array([[14,  0,  0],
       [ 0, 16,  2],
       [ 0,  1, 12]])

## Logistic Regression-- Tensorflow

In [13]:
import tensorflow as tf

2023-06-25 18:44:26.544896: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [14]:
lr_tf = tf.keras.models.Sequential([tf.keras.layers.Dense(units=3, activation='softmax')])
lr_tf.compile(loss=tf.keras.losses.CategoricalCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
              metrics=[tf.keras.metrics.CategoricalAccuracy()]
             )

In [15]:
lr_tf.fit(x=iris_train[iris_from_file["feature_names"]].to_numpy(), 
          y=iris_train[["0", "1", "2"]].to_numpy(), 
          validation_data=(iris_test[iris_from_file["feature_names"]],
                           iris_test[["0", "1", "2"]]), 
          epochs=200)

Epoch 1/200
4/4 [==============================] - 1s 68ms/step - loss: 4.3234 - categorical_accuracy: 0.3048 - val_loss: 3.6676 - val_categorical_accuracy: 0.3778
Epoch 2/200
4/4 [==============================] - 0s 11ms/step - loss: 3.9218 - categorical_accuracy: 0.2667 - val_loss: 3.4222 - val_categorical_accuracy: 0.2889
Epoch 3/200
4/4 [==============================] - 0s 11ms/step - loss: 3.6346 - categorical_accuracy: 0.1048 - val_loss: 3.2615 - val_categorical_accuracy: 0.0444
Epoch 4/200
4/4 [==============================] - 0s 11ms/step - loss: 3.4147 - categorical_accuracy: 0.0381 - val_loss: 3.1144 - val_categorical_accuracy: 0.1556
Epoch 5/200
4/4 [==============================] - 0s 11ms/step - loss: 3.2010 - categorical_accuracy: 0.1524 - val_loss: 2.8922 - val_categorical_accuracy: 0.2000
Epoch 6/200
4/4 [==============================] - 0s 13ms/step - loss: 2.9425 - categorical_accuracy: 0.1429 - val_loss: 2.6232 - val_categorical_accuracy: 0.1556
Epoch 7/200
4/4 

Epoch 51/200
4/4 [==============================] - 0s 13ms/step - loss: 0.5348 - categorical_accuracy: 0.6857 - val_loss: 0.5341 - val_categorical_accuracy: 0.6444
Epoch 52/200
4/4 [==============================] - 0s 13ms/step - loss: 0.5287 - categorical_accuracy: 0.7238 - val_loss: 0.5177 - val_categorical_accuracy: 0.7111
Epoch 53/200
4/4 [==============================] - 0s 13ms/step - loss: 0.5262 - categorical_accuracy: 0.7143 - val_loss: 0.5128 - val_categorical_accuracy: 0.7333
Epoch 54/200
4/4 [==============================] - 0s 15ms/step - loss: 0.5220 - categorical_accuracy: 0.7238 - val_loss: 0.5110 - val_categorical_accuracy: 0.6889
Epoch 55/200
4/4 [==============================] - 0s 15ms/step - loss: 0.5170 - categorical_accuracy: 0.7429 - val_loss: 0.5144 - val_categorical_accuracy: 0.6444
Epoch 56/200
4/4 [==============================] - 0s 15ms/step - loss: 0.5107 - categorical_accuracy: 0.7429 - val_loss: 0.5136 - val_categorical_accuracy: 0.6444
Epoch 57/2

Epoch 101/200
4/4 [==============================] - 0s 10ms/step - loss: 0.3741 - categorical_accuracy: 0.9333 - val_loss: 0.3893 - val_categorical_accuracy: 0.9333
Epoch 102/200
4/4 [==============================] - 0s 9ms/step - loss: 0.3713 - categorical_accuracy: 0.9238 - val_loss: 0.3907 - val_categorical_accuracy: 0.9111
Epoch 103/200
4/4 [==============================] - 0s 10ms/step - loss: 0.3697 - categorical_accuracy: 0.9238 - val_loss: 0.3886 - val_categorical_accuracy: 0.9111
Epoch 104/200
4/4 [==============================] - 0s 10ms/step - loss: 0.3680 - categorical_accuracy: 0.9238 - val_loss: 0.3892 - val_categorical_accuracy: 0.9111
Epoch 105/200
4/4 [==============================] - 0s 9ms/step - loss: 0.3646 - categorical_accuracy: 0.9238 - val_loss: 0.3794 - val_categorical_accuracy: 0.9333
Epoch 106/200
4/4 [==============================] - 0s 10ms/step - loss: 0.3634 - categorical_accuracy: 0.9429 - val_loss: 0.3712 - val_categorical_accuracy: 0.9556
Epoch 

4/4 [==============================] - 0s 9ms/step - loss: 0.2922 - categorical_accuracy: 0.9429 - val_loss: 0.3014 - val_categorical_accuracy: 0.9778
Epoch 151/200
4/4 [==============================] - 0s 9ms/step - loss: 0.2886 - categorical_accuracy: 0.9524 - val_loss: 0.3029 - val_categorical_accuracy: 0.9778
Epoch 152/200
4/4 [==============================] - 0s 9ms/step - loss: 0.2867 - categorical_accuracy: 0.9619 - val_loss: 0.3053 - val_categorical_accuracy: 0.9778
Epoch 153/200
4/4 [==============================] - 0s 10ms/step - loss: 0.2847 - categorical_accuracy: 0.9619 - val_loss: 0.3067 - val_categorical_accuracy: 0.9778
Epoch 154/200
4/4 [==============================] - 0s 9ms/step - loss: 0.2837 - categorical_accuracy: 0.9619 - val_loss: 0.3069 - val_categorical_accuracy: 0.9778
Epoch 155/200
4/4 [==============================] - 0s 9ms/step - loss: 0.2829 - categorical_accuracy: 0.9619 - val_loss: 0.3053 - val_categorical_accuracy: 0.9778
Epoch 156/200
4/4 [====

Epoch 200/200
4/4 [==============================] - 0s 9ms/step - loss: 0.2351 - categorical_accuracy: 0.9619 - val_loss: 0.2621 - val_categorical_accuracy: 0.9778


In [16]:
import numpy as np

predict_values_train = lr_tf.predict(iris_train[iris_from_file["feature_names"]])
predict_train = np.argmax(predict_values_train, axis=1)

predict_values_test = lr_tf.predict(iris_test[iris_from_file["feature_names"]])
predict_test = np.argmax(predict_values_test, axis=1)

2/2 [==============================] - 0s 2ms/step


In [17]:
confusion_matrix(iris_train["target"], predict_train)

array([[36,  0,  0],
       [ 0, 28,  4],
       [ 0,  0, 37]])

In [18]:
confusion_matrix(iris_test["target"], predict_test)

array([[14,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 13]])